name = "addonport-site"
compatibility_date = "2026-08-19"
workers_dev = false

[assets]
directory = "./out"
html_handling = "force-trailing-slash"
not_found_handling = "404-page"

[[routes]]
pattern = "addonport.dev"
custom_domain = true

[[routes]]
pattern = "www.addonport.dev"
custom_domain = true

[observability]
enabled = true
head_sampling_rate = 0.05
